name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name : Trigger name
        run:
            echo " This was triggered by ${{ github.event_name }} event"
            echo " The repo is referencing to ${{ github.ref }} branch"

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
